services:
  - type: web
    name: dmmb
    env: node
    plan: free
    runtime: node
    nodeVersion: 20.10.0
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_BOT_TOKEN
        sync: false # シークレットとして手動で設定する必要あり
    healthCheckPath: /api/status
